name: Greet Every Contributor
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new issue or pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const isPR = github.event_name === 'pull_request';
            const message = isPR
              ? "🚀 Thanks for your pull request! We’ll review it soon."
              : "🎉 Welcome! Thanks for opening your issue! The team will review it soon.";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
