name: Greet Every Contributor
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new contributor
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const isPR = !!context.payload.pull_request;
            const number = isPR ? context.payload.pull_request.number : context.payload.issue.number;
            const type = isPR ? 'pull request' : 'issue';
            const message = isPR
              ? "🎉 Thanks for your pull request! A maintainer will review it soon."
              : "👋 Thanks for opening this issue! We appreciate your contribution.";

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: message
            });
