name: Greet First-Time Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome! Thanks for opening your first issue in AnimateItNow. We’re glad to have you here."
          pr-message: "🎉 Thanks for your first pull request! The team will review it shortly."
